### ISSUE TITLE
Merge two zip files into one with filter

### ISSUE THREAD

**Issue by stefan-reich** [srikanth-lingala/zip4j#404] opened 2022-02-03 03:48 UTC
Hi,

I think zip4j is extremely close to what I want. I want to combines files from two zip files into one, selecting a subset of the files in each. (Without wasting time recompressing the files.)

In net.lingala.zip4j.tasks, I didn't see any tasks involving more than one zip file, so I'll have to tweak things a bit I guess.

I'll probably start my hacking with AddFilesToZipTask...?

Unless someone has done this before.

Greetings and thanks

**Comment by stefan-reich** [comment] 2022-02-03 05:04
OK I'm hacking on it. Basically I am improving RemoveFilesFromZipTask. Let it be known that there are some extreme inefficiencies in that file. Basically when removing m files out of n, it's O(n*m) - instead of O(n+m) which it should be. I like that you made this library but that should definitely be improved!

**Comment by srikanth-lingala** [comment] 2022-06-20 15:18
This is a duplicate of #296. Please track progress on that issue. Closing this one.

**Closed by srikanth-lingala** 2022-06-20 15:18 UTC
Labels: duplicate, new-feature
