### ISSUE TITLE
Cannot add multiple Files + Folders at once? (setRunInThread issue)

### ISSUE THREAD

**Issue by massivemadness** [srikanth-lingala/zip4j#244] opened 2020-10-03 18:51 UTC
There's my file tree that I want to compress:
```
+-- file1.txt
+-- folder1
|   +-- file2.txt
|   +-- file3.txt
```

So I'm adding `file1.txt` and `folder1` in list, and using `ZipFile.addFiles` method to create an archive. But it creates an empty folders even if there were some files inside:
```
+-- file1.txt
+-- folder1 (empty)
```

If I add files and folders manually (using `ZipFile.addFile` and `ZipFile.addFolder`) it works, but since I use `setRunInThread` I'm stuck with `ProgressMonitor.State.BUSY` when adding next file.

(Possible duplicate of #84 ???)

**Comment by srikanth-lingala** [comment] 2020-10-12 15:59
Yes, this is a duplicate of one of #84. I will implement this feature in the next days. But I will close this as duplicate, and will update #84.

**Closed by srikanth-lingala** 2020-10-12 15:59 UTC
Labels: duplicate
