### ISSUE TITLE
net.lingala.zip4j.exception.ZipException: Expected central directory entry not found (#1)

### ISSUE THREAD

**Issue by dancencheung** [srikanth-lingala/zip4j#117] opened 2019-12-10 09:38 UTC
[files.zip](https://github.com/srikanth-lingala/zip4j/files/3967853/files.zip)
For some zip file, I can execute ZipFile.addFile() successfully.
But for other zip file, error happened:
I can execute ZipFile.addFile() without any error; But after that, when I open the zipFile, I do not find the file I added to the zipFile; And I can not open the zipFile(after execute ZipFile.addFile) by zip4j, Exception happened.

Exception:
```
net.lingala.zip4j.exception.ZipException: Expected central directory entry not found (#1)
	at net.lingala.zip4j.headers.HeaderReader.readCentralDirectory(HeaderReader.java:156)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:86)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:851)
	at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:283)
	at net.lingala.zip4j.ZipFile.addFile(ZipFile.java:244)
	at com.dancen.util.filecompressor.MyZipUtil.main(MyZipUtil.java:43)
```

testCode:
```
public static void main(String[] args)
{
	try
	{
		String zipFilePath = "C:\\Users\\zhang\\Desktop\\pro.apk";
		String filePathInZip = "lib/test/test.so";		
		String filePath = "apk/lib/x86/libArmArchEncrypt.so";
		
		ZipParameters zipParameters = new ZipParameters();
		zipParameters.setCompressionMethod(CompressionMethod.DEFLATE);
		zipParameters.setCompressionLevel(CompressionLevel.NORMAL);
		zipParameters.setFileNameInZip(filePathInZip);
		zipParameters.setOverrideExistingFilesInZip(true);
		
		ZipFile zipFile = new ZipFile(zipFilePath);
		zipFile.addFile(new File(filePath), zipParameters);
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
}
```

Test Again, I change the zipParameters, setCompressionMethod as CompressionMethod.STORE, Now everything OK.

TestCode:
```	
public static void main(String[] args)
{
	try
	{
		String zipFilePath = "C:\\Users\\zhang\\Desktop\\pro.apk";
		String filePathInZip = "lib/test/test.so";		
		String filePath = "apk/lib/x86/libArmArchEncrypt.so";
		
		ZipParameters zipParameters = new ZipParameters();
		zipParameters.setCompressionMethod(CompressionMethod.STORE);
		zipParameters.setFileNameInZip(filePathInZip);
		zipParameters.setOverrideExistingFilesInZip(true);
		
		ZipFile zipFile = new ZipFile(zipFilePath);
		zipFile.addFile(new File(filePath), zipParameters);
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
}
```

**Comment by dancencheung** [comment] 2019-12-16 07:03
Waiting for solving ......

**Comment by srikanth-lingala** [comment] 2019-12-16 09:50
I tried your code and see no issue. Can you send me the test files as well (`pro.apk` and `test.so`)?

**Comment by dancencheung** [comment] 2019-12-16 11:54
> I tried your code and see no issue. Can you send me the test files as well (`pro.apk` and `test.so`)?

I have updated the comment by attach the test files, And my system is windows 10.

**Comment by srikanth-lingala** [comment] 2019-12-16 21:11
Issue is identified. Fix is on the way.

**Comment by srikanth-lingala** [comment] 2019-12-18 19:54
Fixed in v2.2.8 released today

**Closed by srikanth-lingala** 2019-12-18 19:54 UTC
Labels: bug

**Comment by dancencheung** [comment] 2019-12-19 07:00
> Fixed in v2.2.8 released today
Thinks.

**Comment by sabariramesh** [comment] 2020-04-07 19:40
Hi, I also facing this same. I have been experiencing this error, when my zip exceeds about 4GB. I am using version 1.3.2. Does this fix solve my issue? Please let me know the root cause, so It help me lot.

**Comment by sabariramesh** [comment] 2020-04-08 10:07
Please let me know the possible cause for this error, so I can debug easily. I am eagerly waiting for your reply @srikanth-lingala

**Comment by srikanth-lingala** [comment] 2020-04-08 17:16
@sabariramesh 

> I am using version 1.3.2. Does this fix solve my issue?

The easiest way to find out is to try upgrading to the latest version of zip4j and see if that fixes it. It is hard for me to say wether it will fix the issue your case or not.

> Please let me know the possible cause for this error, so I can debug easily.

I am not sure how familiar you are with zip specification, but the bug was that zip4j was not copying the extra data records of existing file headers when adding files to an existing zip. This used to only happen in case when the existing file headers had some extra data records.

**Comment by sabariramesh** [comment] 2020-04-15 14:48
Hi   @srikanth-lingala ,
        Thanks for your comments. I have been adding many files to zip at a same time. I am creating new ZipFile for every new files to be added.  Please refer the sample snippet below.
`//getting filename from db
        while(db.hasNext())
        {
            //adding it to zip file
            File zFile = new File(zipfilepath);
            ZipFile zipFile = new ZipFile(zFile);
            zipFile.addFiles(new ArrayList().add(db.getValue("filename")), zipparameters);
        }
    }`
    What is best practice for ZipFile object creation

**Comment by sabariramesh** [comment] 2020-04-17 15:07
@srikanth-lingala , Issue identified. I am opening new ZipFile instance for every file addition.

**Comment by wanjizheng** [comment] 2022-11-08 19:36
Same issue when calling the .extractAll() method. Could you fix it?

**Comment by kris2kris** [comment] 2023-10-25 13:37
in 2.11.5 I have the same issue on extract all too :
`
Caused by: net.lingala.zip4j.exception.ZipException: Expected central directory entry not found (#1)
	at net.lingala.zip4j.headers.HeaderReader.readCentralDirectory(HeaderReader.java:153)
	at net.lingala.zip4j.headers.HeaderReader.readAllHeaders(HeaderReader.java:107)
	at net.lingala.zip4j.ZipFile.readZipInfo(ZipFile.java:1135)
	at net.lingala.zip4j.ZipFile.extractAll(ZipFile.java:462)
`

**Comment by srikanth-lingala** [comment] 2023-10-26 21:27
@kris2kris  Do you have a sample zip file that you can share to reproduce this issue?

**Comment by SalvadorJosa** [comment] 2024-03-27 20:04
> @kris2kris ¿Tiene un archivo zip de muestra que pueda compartir para reproducir este problema?

I have one, but it only allows me to attach 25MB and it weighs almost 200 MB. Where would you like me to send it to you?

**Comment by gordonwhitton** [comment] 2024-05-15 09:59
I am having this issue too, with 2.11.5.  The issue is not present when my test runs on my Windows 10 machine, but occurs when run in circleci on a linux machine
