### ISSUE TITLE
while Extracting the encrypted zip file with third party app with correct password, anyone file is among all files is getting failed and copying with empty data, only one file is happening like that.

### ISSUE THREAD

**Issue by HarishKumar7** [srikanth-lingala/zip4j#277] opened 2021-01-21 04:41 UTC

**Comment by srikanth-lingala** [comment] 2021-01-28 06:56
I am closing this issue as this is a duplicate of #276. Any further progress will be updated in that issue.

And moreover, I appreciate that you reported this issue, but when reporting an issue, please be a bit more specific in your issue description and not the title of the issue. Include as much useful information as possible, like version that you are using, the issue in detail, steps to reproduce, and sample code/zip file if possible. That would help in investigating the issue.

**Closed by srikanth-lingala** 2021-01-28 06:56 UTC
Labels: duplicate
