### ISSUE TITLE
file name will be garbled

### ISSUE THREAD

**Issue by billqs** [srikanth-lingala/zip4j#48] opened 2019-08-18 02:48 UTC
On Windows system platform, the extracted file name will be garbled

**Comment by srikanth-lingala** [comment] 2019-08-18 10:16
There has been an extensive discussion on this on [a recently closed issue][1]. In short the issue most likely is with the tool that created the zip file. A file name has to be encoded in either cp487 or utf8 as per zip specification. If the tool which created this zip file used a different charset, there is no way for zip4j or any other tool for that matter to know which charset was used and this zip file will contain garbled file names when extracting because these are not as per zip specification. 

However, please let me know if this zip file was created with zip4j. In this case this is definitely an issue with zip4j. Please post the code you used to create the zip file along with a sample zip file. If the zip file was not created with zip4j, I cannot help much as the issue with the tool that created the zip file. Please go through the issue linked above, there is a work around mentioned (but you have the know the charset that was used to encode the filename). There is also an issue mentioned with 7zip and a way to fix it in 7zip.

[1]: https://github.com/srikanth-lingala/zip4j/issues/45

**Comment by billqs** [comment] 2019-08-18 12:13
Ok, thank you very much for your maintenance of this project and your reply to my question. I write the project here on the Windows system. On the Windows platform, the default code is GBK, so the most direct way is to set the encoding format.

For example,



ZipFile = new ZipFile(zippath);

ZipFile. SetFileNameCharset (" GBK ");



In this way on the Windows platform there will be no Chinese garbled code

**Comment by billqs** [comment] 2019-08-18 12:22
There is also the problem of using other compression software to encrypt and then unzip using zip4j. Even if a wrong password is entered, the compressed file will be unzipped, but the contents of the file will be empty，I don't quite understand that.

**Comment by srikanth-lingala** [comment] 2019-08-18 13:29
In [this post][1], I explain how to use custom charsets. Replace `euc-kr` with `GBK` equivalent and it should work. I did not want to use custom charsets because they are not officially supported by zip format specification. Zip specification only allows for cp437 and utf8 encoding, and I am really surprised that some well known tools (windows zip util, 7zip, etc) do not obey this specification and therefore break other zip tools.

[1]: https://github.com/srikanth-lingala/zip4j/issues/45#issuecomment-521539061

**Comment by billqs** [comment] 2019-08-18 13:42
ok.thank you very much.I think you should consider the problem of submitting an incorrect decompressed password that can still be decompressed.,I think it important.

**Comment by srikanth-lingala** [comment] 2019-08-18 13:57
Yes, I agree. I think  the problem here is that the FileOutputStream is created before the password check is being done. I will fix it in the next release.

**Comment by billqs** [comment] 2019-08-18 14:13
Ok,Thank you for maintaining this project. Wish you a more popular project.

**Comment by srikanth-lingala** [comment] 2019-08-18 14:29
Thanks

**Comment by srikanth-lingala** [comment] 2019-08-21 20:25
I will close this issue as this is not a bug in zip4j as explained above. Although I will include a fix for the side note mentioned in this issue: zip4j creates empty files when password is wrong. I will include this fix in the next release.

**Closed by srikanth-lingala** 2019-08-21 20:25 UTC
