### ISSUE TITLE
Empty txt file in a zip protected by a password

### ISSUE THREAD

**Issue by chatPerche123** [srikanth-lingala/zip4j#339] opened 2021-07-28 12:03 UTC
Hi, first i'm not an expert in programming. I'm trying to use your work in a personal project with a password protected zip file.
The goal is to find the password of a zip file from a defined list.

The code:
                        zipFile.setPassword(str.toCharArray());
                        try {
                            String fileNameWithOutExt = FilenameUtils.removeExtension(key.getName());
                            zipFile.extractAll("destination_directory/" + fileNameWithOutExt);
                        } catch (ZipException exception) {
                            x++;
                        }

Something strange append when the zip under a password contain an empty txt file. It successfully unlock it without the right input after some try. But if i unzip the file by hand, it ask me for the password.
If the txt file is not empty, it will work like intented.

**Comment by srikanth-lingala** [comment] 2021-08-03 08:01
I just tried this and I was not able to reproduce this issue. Which version of zip4j are you using? Below is the code I used 

```
@Test
public void createZipFile() throws IOException {
  ZipFile zipFile = new ZipFile(BASE_DIR + "sample.zip", "password".toCharArray());
  ZipParameters zipParameters = new ZipParameters();
  zipParameters.setEncryptFiles(true);
  zipParameters.setEncryptionMethod(EncryptionMethod.AES);
  zipFile.addFile(new File(BASE_DIR + "empty_file.txt"), zipParameters);
}

@Test
public void readZip() throws IOException {
  File fileToRead = new File(BASE_DIR + "sample.zip");
  ZipFile zipFile = new ZipFile(fileToRead);
  zipFile.extractAll(OUTPUT_DIR);
}
```

I get this exception, which is the desired behaviour:

`net.lingala.zip4j.exception.ZipException: empty or null password provided for AES decryption`

And when I used a wrong password, I get this exception:

`net.lingala.zip4j.exception.ZipException: Wrong Password`

**Comment by srikanth-lingala** [comment] 2021-09-05 19:27
I am closing this issue, as there was no further feedback from the user, and also since I was not able to reproduce the issue. Refer to the comment above for more details.

**Closed by srikanth-lingala** 2021-09-05 19:27 UTC
Labels: want feedback
