### ISSUE TITLE
ProgressMonitor with in setRunInThread(false)

### ISSUE THREAD

**Issue by lzxshare** [srikanth-lingala/zip4j#382] opened 2021-11-08 09:29 UTC
I think use ProgressMonitor to get progress is not very friendly, especially in setRunInThread(false) settings, we can‘t get progress, maybe use Progress Listener is a common and better  way. Do you have any plans for improvement？ many thanks

**Comment by srikanth-lingala** [comment] 2021-11-09 09:45
Yes, I agree that a listener is a better way. There should also be another similar issue open here. As mentioned in the other issue, I will try my best to get this feature in the free time I might get in December.

**Comment by srikanth-lingala** [comment] 2021-11-10 06:06
This is a duplicate of #340. Please follow that issue for updates.

**Closed by srikanth-lingala** 2021-11-10 06:06 UTC
Labels: duplicate
