### ISSUE TITLE
Crash after upgrade to 2.5.0 (Android)

### ISSUE THREAD

**Issue by MoNTE48** [srikanth-lingala/zip4j#161] opened 2020-03-20 10:31 UTC
```
net.lingala.zip4j.exception.ZipException: Could not fill buffer
        at net.lingala.zip4j.util.RawIO.readFully(RawIO.java:155)
        at net.lingala.zip4j.util.RawIO.readIntLittleEndian(RawIO.java:85)
        at net.lingala.zip4j.headers.HeaderReader.readLocalFileHeader(HeaderReader:551)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:85)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:77)
        at com.***.***.UnzipService.unzip(UnzipService.java:98)
        at com.***.***.UnzipService.onHandleIntent(UnzipService.java:48)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

Android 4-10

**Comment by joorei** [comment] 2020-03-21 09:25
The cause seems to be that the `InputStream` backing `ZipInputStream` has not even 4 bytes left when `getNextEntry()` is called.

The reason for that **may** be that `getNextEntry()` is called when there are no more `LocalFileHeader` to get (ie. the backing `InputStream` is completely empty). Do you have access to `UnzipService` and can look up how it is using the `ZipInputStream`? Are there any checks before `getNextEntry()` is called or how often it is called?

**Comment by srikanth-lingala** [comment] 2020-03-21 10:43
Are you able to extract the zip file using a previous version of zip4j? It seems that there was an issue reading the zip file. It might be because of several reasons (corrupt zip file, os not allowing reading of file, etc). Could it be a permission issue to read file on Android? Would it be possible for you to share the zip file?

**Comment by MoNTE48** [comment] 2020-03-21 13:30
I can not give any additional information. This is a rare crash in crashlytics.
Changes in the application compared to the previous release: updating the advertising library, the new version of zip4j, the translation of several strings.

**Comment by srikanth-lingala** [comment] 2020-03-21 13:34
Unfortunately, without any further information it will be near impossible to figure out the root cause. All I can say from the error message is that zip4j could not read enough data from the file that was being read. It was expecting to read 4 bytes from the file, but could not read the complete 4 bytes. This is the first information that is being read from the file, so the cause for this issue might be either a corrupt zip file or zip4j (and the jvm it is running on) does not have read access to the zip file. And from the information I currently have, I believe this is not an issue with zip4j.

**Comment by MoNTE48** [comment] 2020-03-21 13:47
Perhaps there was a problem with copying the archive from apk. But this error did not appear earlier. Only after updating zip4j. I will return to the old version in this case.
Maybe you should make an exception instead of an error...

**Comment by srikanth-lingala** [comment] 2020-03-22 10:31
You mean to say that for the same zip file, this error did not occur with an earlier version of zip4j? Which version of old zip4j were you using? 

> Maybe you should make an exception instead of an error...

Zip4j throws an exception and not an error when this issue happens. Even from your stacktrace, it is a `ZipException`. `ZipException` extends `IOException` which extends `Exception`.

**Comment by MoNTE48** [comment] 2020-03-23 20:59
Having reviewed more of the history of crashlytics, I noticed this on older versions. Most likely, some kind of error occurs when copying the archive from the APK to the device’s memory.
Because of this, the decompression is broken.
Here are similar errors:

`net.lingala.zip4j.exception.ZipException: Reached end of entry, but crc verification failed for *******`

`
java.lang.ArrayIndexOutOfBoundsException: length=12; regionStart=-1; regionLength=13
        at java.util.Arrays.checkOffsetAndCount(Arrays.java:1731)
        at java.io.PushbackInputStream.read(PushbackInputStream.java:180)
        at net.lingala.zip4j.io.inputstream.ZipEntryInputStream.readUntilBufferIsFull(ZipEntryInputStream:78)
        at net.lingala.zip4j.io.inputstream.ZipEntryInputStream.readRawFully(ZipEntryInputStream:62)
        at net.lingala.zip4j.io.inputstream.CipherInputStream.readRaw(CipherInputStream.java:70)
        at net.lingala.zip4j.io.inputstream.ZipStandardCipherInputStream.getStandardDecrypterHeaderBytes(ZipStandardCipherInputStream.java:24)
        at net.lingala.zip4j.io.inputstream.ZipStandardCipherInputStream.initializeDecrypter(ZipStandardCipherInputStream.java:19)
        at net.lingala.zip4j.io.inputstream.ZipStandardCipherInputStream.initializeDecrypter(ZipStandardCipherInputStream.java:11)
        at net.lingala.zip4j.io.inputstream.CipherInputStream.<init>(CipherInputStream.java:24)
        at net.lingala.zip4j.io.inputstream.ZipStandardCipherInputStream.<init>(ZipStandardCipherInputStream.java:14)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.initializeCipherInputStream(ZipInputStream.java:212)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.initializeEntryInputStream(ZipInputStream.java:200)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:106)
        at net.lingala.zip4j.io.inputstream.ZipInputStream.getNextEntry(ZipInputStream.java:79)
        at com.***.***.UnzipService.unzip(UnzipService.java:102)
        at com.***.***.UnzipService.onHandleIntent(UnzipService.java:48)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:177)
        at android.os.HandlerThread.run(HandlerThread.java:60)
`

**Comment by srikanth-lingala** [comment] 2020-03-25 12:36
It looks like this issue is specific to your environment/testing. I have not heard of such errors from other Android users. It does not seem to be an issue with zip4j. I am closing this issue. Feel free to re-open with more info if you seem to find any specific issue with zip4j.

**Closed by srikanth-lingala** 2020-03-25 12:36 UTC
Labels: want feedback
