### ISSUE TITLE
Multi-thread support

### ISSUE THREAD

**Issue by lzxshare** [srikanth-lingala/zip4j#381] opened 2021-11-08 09:21 UTC
yes,i think Multi-thread is very useful in some scenarios，especially when dealing with large files, I hope the author can realize this function as soon as possible，many thanks

**Comment by srikanth-lingala** [comment] 2021-11-09 09:44
I will most likely have some free time from first week of December. I will see if I can add this feature during that time.

**Comment by srikanth-lingala** [comment] 2021-11-10 06:05
This is a duplicate of #319. Please follow that issue for updates

**Closed by srikanth-lingala** 2021-11-10 06:05 UTC
Labels: duplicate
