### ISSUE TITLE
Error extracting zip larger than 4 gigabyte

### ISSUE THREAD

**Issue by heberpimentel** [srikanth-lingala/zip4j#71] opened 2019-09-26 13:38 UTC
Good Morning,
I generated a 12 gigabyte zip, and can't extract the files on windows and linux.
Depending on the size of the zip, I can extract but lose data. This from 4 gigabyte.
        zipParameters = new ZipParameters();
        zipParameters.setEncryptFiles(true);
        zipParameters.setEncryptionMethod(EncryptionMethod.AES);
        zipParameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
        zipParameters.setCompressionLevel(CompressionLevel.NORMAL);

**Comment by heberpimentel** [comment] 2019-09-26 13:50
A note: I can extract using zip4j but not with linux and windows applications. If I zip with windows or linux applications, it works normally.

**Comment by nicolabeghin** [comment] 2019-09-26 14:21
this could depend on the app you're using to extract, since with such big size `zip4j` should automatically use [ZIP64](https://en.wikipedia.org/wiki/Zip_(file_format)#ZIP64) in place of standard ZIP

**Comment by heberpimentel** [comment] 2019-09-26 14:24
I have used 7zip or 7z and not used unzip

**Comment by heberpimentel** [comment] 2019-09-26 14:29
Do you have any recommendations for a program so I can do some more testing? Sorry for English'

**Comment by nicolabeghin** [comment] 2019-09-26 14:34
AFAIK [7-zip supports ZIP64](https://sevenzip.osdn.jp/chm/general/formats.htm) so I don't see a reason why it shouldn't work.. @srikanth-lingala any hint on this?

**Comment by LeeYoung624** [comment] 2019-09-27 08:36
No doubt that Zip64 is working in your use case. Considering the size of the zip file, asking you to provide the zip file is a bad idea.

Please allow me to make it clear: 
You are trying to zip 12 GB files into a zip file using zip4j. You can only extract the zip file generated by zip4j when using zip4j, not 7zip/unzip. When you zip these file using other libraries like 7zip, it could be extracted by zip4j and 7zip. Am I right?

**Comment by srikanth-lingala** [comment] 2019-09-27 09:32
@heberpimentel @nicolabeghin I will try to reproduce this and update the thread. We have tests here for Zip64 format, but the zip file is created and extracted by zip4j, and if I understand correctly, the issue comes when the huge zip file is created with other tools.

**Comment by heberpimentel** [comment] 2019-09-27 13:00
A note: I generate a zip with several files in various formats (video, image, documents) .. and who will use will not have zip4j

**Comment by srikanth-lingala** [comment] 2019-09-27 13:32
Thanks for correcting me.

**Comment by srikanth-lingala** [comment] 2019-09-29 19:28
Fixed in v2.2.1

**Closed by srikanth-lingala** 2019-09-29 19:28 UTC
Labels: bug
