### ISSUE TITLE
Extraction on Android failing due to too many open files

### ISSUE THREAD

**Issue by nicolabeghin** [srikanth-lingala/zip4j#34] opened 2019-08-03 14:07 UTC
Hi everyone 
I'm experiencing a strange issue with a ZIP file both created and extracted with zip4j 2.1.1.
The file is created on the desktop and extracted on Android, leading to this exception and Android rebooting (!!!)

> 6847-8599/system_process E/art: ashmem_create_region failed for 'indirect ref table': Too many open files

Full exception when extracting on Android:
```
Process: com.xyz, PID: 6504
    java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
        at android.view.InputChannel.nativeReadFromParcel(Native Method)
        at android.view.InputChannel.readFromParcel(InputChannel.java:148)
        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:841)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:640)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:322)
```

As a reference, the same extraction Android code works with a ZIP file created through Apache Commons Compress:

    private boolean decompress() {
        final File targetFolder = file.getParentFile();
        final File existingMediaFolder = new File(targetFolder, "Media");
        cleanupExistingMediaFolder(existingMediaFolder);
        targetFolder.mkdirs();
        try {
            ZipFile zipFile = new ZipFile(file);
            zipFile.setRunInThread(true);
            ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
            zipFile.extractAll(targetFolder.getAbsolutePath());
            while (progressMonitor.getState() == ProgressMonitor.State.BUSY) {
                publishProgress(progressMonitor.getPercentDone());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            FLog.e(MainActivity.AppName, ex.getMessage());
            cleanupExistingMediaFolder(existingMediaFolder);
            return false;
        }
        return true;
    }

This is the problematic compress code on Java desktop (as wrote, recently switched from Apache Commons Compress, which had no issue - I wanted to unify the compress/decompress through zip4j):

    private void compressToZip() throws Exception {
        numFiles = countFiles(folder.toPath());
        App.LOG.info("Compressing " + numFiles + " files to " + targetZip.getAbsolutePath());
        updateProgress(0, 100);
        ZipParameters zipParameters = new ZipParameters();
        zipParameters.setCompressionMethod(CompressionMethod.STORE);
        ZipFile zipFile = new ZipFile(targetZip);
        ProgressMonitor progressMonitor = zipFile.getProgressMonitor();
        zipFile.setRunInThread(true);
        zipFile.addFolder(folder, zipParameters);
        while (!progressMonitor.getState().equals(ProgressMonitor.State.READY)) {
            updateProgress(progressMonitor.getPercentDone(), 100);
            updateMessage(String.format(getString("compressing.d.out.of.d"), numFiles));
            if (isCancelled()) {
                return;
            }
        }
        App.LOG.info(String.format("Compressed successfully to %s (%s)", targetZip.getAbsolutePath(), HumanReadableSize.humanReadableByteCount(targetZip.length())));
    }

Any idea on this?

thanks
nicola

**Comment by srikanth-lingala** [comment] 2019-08-05 15:21
Unfortunately I am not an Android expert, so I cannot try to reproduce this issue myself. Therefore I would like to ask for your help in investigating this issue (If you can suggest me a way to reproduce this issue myself, I would be more than happy to do so).

With zip4j, extraction of a zip file will not be dependent on the source of creation of a zip file (be it zip4j or apache commons). Can you please confirm that the number of files in both the zip files (created by apache commons and zip4j) are the same? And also, would it be possible for you to debug [ZipInputStream.close][1] and see if the close method is actually being called? I would also suggest to "Step into" in the debug mode all the way down and see if all the underlying inputstreams are being closed as well. Thanks.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/io/inputstream/ZipInputStream.java#L140

**Comment by srikanth-lingala** [comment] 2019-08-06 06:47
And also, can [this][1] be the reason? Zip4j uses try-with-resources to close its streams. I am not sure if the version of Android you are using supports it.

To me it looks like the files that are being extracted by zip4j are not properly closed. [This][2] is the code with try-with-resources that should close all the extracted files. As you see this uses try-with-resource code. I tested in on my local machine and close method is called. If your version of Android does not support it, it might be that the close method on extracted file is not being called. Can you please let me know the version of Android you are using. And as suggested earlier, can you please set a breakpoint and see if the close method is being called, especially in AbstractExtractFileTask and not necessarily in ZipInputStream as suggested in above post.

[1]: https://stackoverflow.com/a/24290875/2736153
[2]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/tasks/AbstractExtractFileTask.java#L69

**Comment by nicolabeghin** [comment] 2019-08-06 07:04
Thanks @srikanth-lingala I'll try to debug this, but I'm not sure it's related to the input streams not closed, since the same code works totally ok on a ZIP created by Apache Commons. If you want, I can send the ZIP file for your reference (maybe an email address?). In order to recreate, for your reference, it's enough to decompress with the basic code in `decompress()`.

**Comment by srikanth-lingala** [comment] 2019-08-06 08:18
Please send the zip files to srikanth.mailbox@gmail.com. Please include the one created with Apache Commons and also the one created with Zip4j. Thanks

**Comment by nicolabeghin** [comment] 2019-08-06 19:30
Thanks a lot @srikanth-lingala just sent!

**Comment by srikanth-lingala** [comment] 2019-08-06 20:20
I still haven't got it. Maybe it takes a while.

> In order to recreate, for your reference, it's enough to decompress with the basic code in decompress() in any Android project.

And here is where my problem is. I cannot code in Android. Maybe I can find a quick tutorial to get a very basic Android project running locally. I will try my best once I get the zip files. At the very least, I will try with the sample zip on my machine to reproduce it, but I am afraid it will not be the same environment as trying it on an Android. Lets see. I will update this thread once I test it.

**Comment by nicolabeghin** [comment] 2019-08-06 22:01
Did you get it? Just to be sure (don't want to bother you) added on hangout too. I could create a basic android project for testing

**Comment by srikanth-lingala** [comment] 2019-08-07 05:18
Got it (it was in my spam folder). It would be great if you can give me a very basic Android project to test this issue.

**Comment by nicolabeghin** [comment] 2019-08-08 20:30
Sorry for the late reply, I just created a basic Android project with zip4j, you can find it here https://github.com/nicolabeghin/zip4jtest

FYI I couldn't recreate the issue plus it works now in the target app, don't know what to think... :D - hope you can find the basic project useful for testing zip4j on Android, huge potential in my opinion!

**Comment by srikanth-lingala** [comment] 2019-08-09 12:24
Thanks for the Android project. It will be helpful for me in the future. 

Based on your comment, I will now closed this issue. Let me know if you see such behaviour again.

**Closed by srikanth-lingala** 2019-08-09 12:24 UTC
Labels: Not an issue
