### ISSUE TITLE
Cannot delete zip file after adding folder to zip

### ISSUE THREAD

**Issue by jwkuaile** [srikanth-lingala/zip4j#218] opened 2020-07-13 12:11 UTC
new ZipFile("filename.zip").addFolder(new File("/user/myuser/folder_to_add"));

请问使用这个方法 ，最后一个ZIP压缩文件的java进程如何释放呢？

thank you very much！

**Comment by srikanth-lingala** [comment] 2020-07-17 13:42
Please report your issue in English.

**Comment by jwkuaile** [comment] 2020-07-18 14:56
new ZipFile("filename.zip").addFolder(new File("/user/myuser/folder_to_add"));

I use the above method. The permission of the last zip file is not released (for example, if I delete it, I can't delete it). What should I do now?

thank you very much！

**Comment by srikanth-lingala** [comment] 2020-07-21 19:04
which OS are you on? Windows? Mac? Linux?

**Comment by jwkuaile** [comment] 2020-07-22 13:22
Windows

thank you very much！

**Comment by srikanth-lingala** [comment] 2020-08-24 10:42
I tried this on a windows machine, and I was able to delete the zip file successfully. Which version of zip4j are you using? If you are on an older version of zip4j, can you please try with the latest version?

**Comment by srikanth-lingala** [comment] 2020-08-25 06:56
And also, are you sure that there is no handle left open in your code for that file?

**Comment by jwkuaile** [comment] 2020-08-27 06:13
Did not stop the service to delete the file

I use the version: 2.6.1

**Comment by srikanth-lingala** [comment] 2020-09-02 06:46
But, my question was if you were sure if there is a file handle open in any other part of your code? Because I could not reproduce this locally. Would it be possible to attach the zip file?

**Comment by srikanth-lingala** [comment] 2020-10-12 15:55
Closing this issue as there is no further feedback. Please feel free to reopen if you have any feedback to my question above.

**Closed by srikanth-lingala** 2020-10-12 15:55 UTC
Labels: want feedback
