### ISSUE TITLE
Can't unzip file on MacOS Catalina

### ISSUE THREAD

**Issue by ephigabay** [srikanth-lingala/zip4j#86] opened 2019-10-13 11:10 UTC
I'm generating a zip file using zip4j, and it opens perfectly on older MacOS but since upgrading to Catalina I get the following error:
"Unable to expand <filename> into 'Downloads'. (Error 79 - Inappropriate file type or format.)"
After playing with the code a bit I narrowed it down to happening only when using streams (`addStream`) and the compression method is "deflate".
Looking at the logs in the Console I saw this error:
"[ERROR] Couldn't read the header of the entry: Error Domain=NSPOSIXErrorDomain Code=79 UserInfo={NSURL=<private>, NSDebugDescription=<private>}"
Unzipping with the command line works fine.
Tested on the newest version (2.2.2).
Attaching an example zip file.

[example.zip](https://github.com/srikanth-lingala/zip4j/files/3721663/example.zip)

**Comment by srikanth-lingala** [comment] 2019-10-13 12:51
Issue fixed. Will include it in the next release.

**Comment by ephigabay** [comment] 2019-10-13 12:55
@srikanth-lingala Thanks!

**Comment by srikanth-lingala** [comment] 2019-10-19 06:12
Fixed in v2.2.3

**Closed by srikanth-lingala** 2019-10-19 06:12 UTC
Labels: bug, resolved

**Comment by halfdan** [comment] 2020-03-09 15:09
@srikanth-lingala Hi there! I'm facing a similar issue currently in an unrelated project.  Would you mind explaining what was wrong and how your fix made the produced files compatible with Catalina?

**Comment by srikanth-lingala** [comment] 2020-03-09 19:57
@halfdan For entries in zip which had extra data record (crc, compressed and uncompressed sizes after the end of data), zip4j was writing uncompressed size as -1 in the local file header, which in theory should not matter because the actual size is in the extra data record. But I guess there were some additional checks added to the zip utility in Catalina, and in those cases where zip4j wrote -1, the zip files could not be opened on Catalina (used to work fine on older versions of Mac). Fix was to write 0 instead of -1. Hope that helped.

**Comment by lomchik** [comment] 2021-02-16 16:07
This problem again occurred on Mac Os Big Sur v11.1. An archive can not be opened with the default Archive Utility.
But the same file can be opened with  terminal unzip utility or with The Unarchiver. 
[test.zip](https://github.com/srikanth-lingala/zip4j/files/5989912/test.zip)

@srikanth-lingala please reopen issue.

**Comment by srikanth-lingala** [comment] 2021-02-18 06:12
@lomchik I have created a new issue #286 from what you have mentioned. The root cause of both these issues are different, and it doesn't make sense to reopen this issue. Please follow the other issue for updates and the reason for this issue.
