### ISSUE TITLE
get an error when call createSplitZipFileFromFolder function

### ISSUE THREAD

**Issue by yuweiming2016** [srikanth-lingala/zip4j#251] opened 2020-10-15 02:25 UTC
![image](https://user-images.githubusercontent.com/22490427/96069383-b0f89680-0ed0-11eb-866f-a769f770b75d.png)

zip4j version:2.6.1
code as follow：

  public static void main(String[] args) throws Exception {
    ZipFile zipFile = new ZipFile("/out.zip");
    // 编码格式
    Charset gbk = Charset.forName("GBK");
    zipFile.setCharset(gbk);
    ZipParameters parameters = new ZipParameters();
    parameters.setCompressionMethod(CompressionMethod.DEFLATE);
    parameters.setCompressionLevel(CompressionLevel.NORMAL);
    zipFile.createSplitZipFileFromFolder(new File("/黄燕-数据整理"), parameters, true, 65536L);
  }

**Comment by srikanth-lingala** [comment] 2020-10-15 08:05
When zip4j creates split zip files, it first creates a file with a temporary name, and then renames the file (to example: out.z01, etc) when the split limit has been reached. Unfortunately, zip4j was not able to rename the file in your case, because it might be that a file with that name already exists in that output directory, or because the process that zip4j is running in does not have enough permissions to rename a file. Can you check if any of them is valid?

**Comment by yuweiming2016** [comment] 2020-10-21 01:59
![image](https://user-images.githubusercontent.com/22490427/96663745-e34c3d00-1383-11eb-966a-dbc823c25f13.png)
i don't think the reason about  permissions 
i can rename manually.   please check

**Comment by yuweiming2016** [comment] 2020-10-21 02:07
![image](https://user-images.githubusercontent.com/22490427/96664312-1216e300-1385-11eb-9609-a0173d8d2a82.png)
the above code can be renamed successfully

**Comment by srikanth-lingala** [comment] 2021-02-08 03:53
This obviously does not happen in all cases. I have tested this feature on my machine, and also there are Integration Tests for split zip. I have a Windows 7 machine. I will try on it to reproduce on it.

**Comment by srikanth-lingala** [comment] 2021-02-08 06:15
I tried this on a Windows 7 machine as well, and it worked perfectly fine for me. This might be something to do with your machine than zip4j. The only difference is that I tried with the latest version of zip4j (2.6.4). Maybe try upgrading to this version and see if that works.

**Comment by srikanth-lingala** [comment] 2021-02-15 04:12
Closing this issue, as this issue was not reproducible as mentioned above. All tests on different OS worked fine. Please feel free to reopen if you are able to let me know a way to reproduce this issue.

**Closed by srikanth-lingala** 2021-02-15 04:12 UTC
Labels: not an issue
