### ISSUE TITLE
password protected zipfile on s3

### ISSUE THREAD

**Issue by nikhiljain1911** [srikanth-lingala/zip4j#314] opened 2021-04-29 16:55 UTC
I need to upload a password protected zipfile on Amazon S3 , file is being uploaded and can be downloaded from Amazon S3, but while opening the file it is showing me the error :" An error occured while loading the archive".
I am setting the Zi[pParameters as below:
parameters.setCompressionMethod(Zip4jConstants.COMP_AES_ENC);
        parameters.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_NORMAL);
        parameters.setEncryptFiles(true);
        parameters.setEncryptionMethod(Zip4jConstants.ENC_METHOD_AES);
        parameters.setAesKeyStrength(Zip4jConstants.AES_STRENGTH_128);
        parameters.setPassword("password");

Can someone please help me out either in changing the parameters or in some other way?

**Comment by nikhiljain1911** [comment] 2021-04-29 16:59
@srikanth-lingala I am currently using 1.3.3 version. Can you please suggest me some newer version and configurations for s3?

**Comment by srikanth-lingala** [comment] 2021-04-29 17:05
Were you able to successfully extract the zip file before you uploaded the zip file?
Did you try with the latest version of zip4j?
What is the stacktrace? This error message `An error occured while loading the archive` is not from zip4j.
Did you compare the zip files before and after uploading/downloading? Not just the file sizes, but also the crc of the file?

**Comment by nikhiljain1911** [comment] 2021-04-29 17:16
In the latest version of zip4j, I am unable to find the password(setPassword) function.
Actually I am not creating that zipfile in my local, I am directly loading that file through zipoutput stream.

**Comment by srikanth-lingala** [comment] 2021-04-29 17:20
You can set password with ZIpOutputStream constructor. I do not support 1.x version of zip4j anymore. There were a lot of bugs fixed in 2.x and it might very well be that the issue is fixed in 2.x. Would you be able to attach a sample zip file here?

**Comment by nikhiljain1911** [comment] 2021-04-29 17:35
![zip](https://user-images.githubusercontent.com/43957510/116593926-43c5c380-a93f-11eb-8ed5-90d2eb42e9e1.png)
This is the code snippet

**Comment by srikanth-lingala** [comment] 2021-04-29 17:40
I see nothing wrong with the code (related to zip file generation). But again, this is with 1.x and I do not support it. Please use the latest version and see if that helps.

**Comment by nikhiljain1911** [comment] 2021-04-29 17:48
Let me try with the newer version and will let you know if found any issue.
Although thanks for your greak work!

**Comment by nikhiljain1911** [comment] 2021-04-29 18:12
![zip1](https://user-images.githubusercontent.com/43957510/116598028-f9931100-a943-11eb-83fc-fbad176a1556.png)

Referring to the above code snippet, I want to say that in 2.x version, password needs to be attached to zipFile being created; but in 1.x version it was being added in Zipparameters.
I mentioned earlier that I don't want to create a file in my local, so I want to add password in my ZipParameters, not directly to the file. So can you please suggest me a way to add Password in my ZipParameters itself.

**Comment by srikanth-lingala** [comment] 2021-04-29 18:16
With zip4j 2.x, password has to be passed in through the constructor of the ZipOutputStream if you are using the ZipOutputStream or if you are using ZipFile, you can pass in either with the constructor or with `ZipFle.setPassword()` method.

**Comment by srikanth-lingala** [comment] 2021-05-03 11:46
@nikhiljain1911 Did you get this resolved with the latest version?

**Comment by srikanth-lingala** [comment] 2021-05-17 13:17
@nikhiljain1911 I am closing this issue as there was no further feedback from you. Please feel free to reopen if you have any feedback on my point above.

**Closed by srikanth-lingala** 2021-05-17 13:17 UTC
Labels: want feedback
