### ISSUE TITLE
randomAccessFile not closed properly causing zipfiles to be locked

### ISSUE THREAD

**Issue by jellylee2020** [srikanth-lingala/zip4j#90] opened 2019-10-17 19:42 UTC
in ZipFile.java
  in readZipInfo function
    please add randomAccessFile.close() to close the file so the file will be released.

**Comment by srikanth-lingala** [comment] 2019-10-17 20:01
If you are referring to [this part of the code][1], the RandomAccessFile is initialised in a [try-with-resources block][2]. The RandomAccessFile will automatically be closed by the jvm after the code block is executed.

[1]: https://github.com/srikanth-lingala/zip4j/blob/master/src/main/java/net/lingala/zip4j/ZipFile.java#L845
[2]: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by jellylee2020** [comment] 2019-10-17 22:00
it does not get released unfortunately.  try remove the zip file after
execute the following statement to get header, the file will be reported to
be locked by jvm

1.  ZipFile zipFile = new ZipFile(f);
2.  List<FileHeader> fileHeaderList = zipFile.getFileHeaders();

at least under windows.  In debug, after executing statement 1, the file
referred to by f is removable.  After executing statement 2, the file is
locked until jvm exits.

**Comment by srikanth-lingala** [comment] 2019-10-19 05:18
I tried it today on a windows machine, and unfortunately could not reproduce this issue. I tried the same way mentioned in your post above. The test succeeds and also the file was deleted. I tried with several paths and several zip files and still the file was deleted successfully each time.

```
@Test
public void deleteZipFileAfterReadingHeaders() throws IOException {
  File sourceFile = new File("C:\\Users\\Srikanth\\Desktop\\tmp\\sample.zip");
  
  ZipFile zipFile = new ZipFile(sourceFile);
  zipFile.getFileHeaders();

  assertThat(sourceFile.delete()).isTrue();
}
```

Maybe there is a file handle open somewhere else within your code?

**Comment by srikanth-lingala** [comment] 2019-10-24 09:43
Closing this issue as there was no further feedback on this. Feel free to reopen if you think there is an issue with zip4j, but in that case, please also provide as much relevant information as possible, like the code you use, etc. With the code sample in your post, I was not able to reproduce this issue.

**Closed by srikanth-lingala** 2019-10-24 09:43 UTC
Labels: Not an issue

**Comment by jellylee2020** [comment] 2019-10-28 03:22
I'm using it in an application bean on glassfish 4.1.2.  Could that be the
problem?

**Comment by srikanth-lingala** [comment] 2019-10-28 07:00
Probably. Unfortunately, I can't say that for sure.
