### ISSUE TITLE
InputStream cannot be get from a zip file

### ISSUE THREAD

**Issue by azhao-2019** [srikanth-lingala/zip4j#46] opened 2019-08-15 09:11 UTC
I want to get inputStream from a zip file, but it is always empty.
This means that InputStream can not be used properly and can not get the bytes inside.
Because the length of InputStream is 0.

//Case 1:  I used failure cases.

	public InputStream getInputStream() {
		// 1. get the inputStream， it size( or length) is empty.
		ZipFile zipFile = new ZipFile("filename.zip");
		FileHeader fileHeader = zipFile.getFileHeader("entry_name_in_zip.txt");
		InputStream inputStream = zipFile.getInputStream(fileHeader);
		return inputStream;
	}

	//1.2 get the inputStream， it size( or length)  is empty. 
	public void extractWithZipInputStream(File zipFile, char[] password) throws IOException {
		LocalFileHeader localFileHeader;
		int readLen;
		byte[] readBuffer = new byte[4096];
		
		try (FileInputStream fileInputStream = new FileInputStream(zipFile); ZipInputStream zipInputStream = new ZipInputStream(fileInputStream, password)) {
			while ((localFileHeader = zipInputStream.getNextEntry()) != null) {
				File extractedFile = new File(localFileHeader.getFileName());
				try (OutputStream outputStream = new FileOutputStream(extractedFile)) {
					while ((readLen = zipInputStream.read(readBuffer)) != -1) {
						outputStream.write(readBuffer, 0, readLen);
					}
				}
			}
		}
	}

//Case 2: I get inputStream success,  but it's not good.
//when zipInputStream  is empty, i use api( zipFile.extractFile(xx, xx)), get unzip file, 
// then i can new  inputStream success.
// int fact, i don't want get the unzip file.

	private static InputStream getCerInputStream(ZipFile zipFile, Context context) throws Exception {
		List<FileHeader> fileHeaders = zipFile.getFileHeaders();
		int size = fileHeaders.size();
		SugrLog.i(TAG, "size = " + size);
		
		for (int i = 0; i < size; i++) {
			FileHeader fileHeader = fileHeaders.get(i);
			
			SugrLog.i(TAG, "name = " + fileHeader.getFileName());
			ZipInputStream zipInputStream = zipFile.getInputStream(fileHeader);
			SugrLog.i(TAG, " zipInputStream = " + (zipInputStream == null));
			
			if (zipInputStream != null){
				// TODO: size = 0 , There's a problem. zipInputStream shouldn't be zero.
				SugrLog.i(TAG, " zipInputStream size= " + zipInputStream.available());
				
				if ( zipInputStream.available() > 0){
					return zipInputStream;
				}
				zipInputStream.close();
			}
			
			//unzip test
			String cachePath = context.getFilesDir().getPath();
			zipFile.extractFile(fileHeader.getFileName(), cachePath);
			String cachePath33 = context.getFilesDir().getPath() + File.separator + fileHeader.getFileName();
			FileInputStream inputStream = new FileInputStream(cachePath33);
			
			File file = new File(cachePath33);
			if (file.exists()){
				file.delete();
			}
			
			SugrLog.i(TAG, "inputStream size = " + inputStream.available());
			return inputStream;
		}

		return null;
	}

**Comment by srikanth-lingala** [comment] 2019-08-15 09:21
Can you please attach the zip file you used? Thanks

**Comment by azhao-2019** [comment] 2019-08-15 09:37
[demo.txt](https://github.com/srikanth-lingala/zip4j/files/3505028/demo.txt)
[cache.zip](https://github.com/srikanth-lingala/zip4j/files/3505039/cache.zip)

I can't provide the files I tested, but I also failed to use a demo file.      password :Z1oEOdbWGwSYlWgtJXVan8eMbNKFUVRmWALoDvkgy2vJQaIEYmHEgyU4552li6RD

**Comment by srikanth-lingala** [comment] 2019-08-18 12:32
With your attached zip file, the first code worked fine for me:

```
ipFile zipFile = new ZipFile("/Users/slingala/Downloads/cache.zip", "Z1oEOdbWGwSYlWgtJXVan8eMbNKFUVRmWALoDvkgy2vJQaIEYmHEgyU4552li6RD".toCharArray());

// 1. get the inputStream， it size( or length) is empty.
FileHeader fileHeader = zipFile.getFileHeader("demo001.txt");
InputStream inputStream = zipFile.getInputStream(fileHeader);
int readLen;
byte[] readBuffer = new byte[4096];

ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
while ((readLen = inputStream.read(readBuffer)) != -1) {
  byteArrayOutputStream.write(readBuffer, 0, readLen);
}
System.out.println("File Content: " + new String(byteArrayOutputStream.toByteArray()));
byteArrayOutputStream.close();
inputStream.close();
```

With the other examples however, there is an issue with the zip file you attached. The zip file is not properly created. The file in the zip file is of compression method store (not deflate), and this entry has an extra data field flag set. In such cases, it is expected that the tool which created the zip file stores the actual size of the file in the local file header, but unfortunately it stored a 0. Therefore zip4j cannot extract the content correctly. The issue lies with the tool that was used to create the file. With such zip files, using the ZipFile api will not be a problem, but using a ZipInputStream will be a problem because size is 0 in one file header. I think you should report this issue to the tool that was used to create the zip file.

**Comment by srikanth-lingala** [comment] 2019-08-21 06:03
Closing this issue as there is no further feedback and also because the issue is with the tool that created the zip file.

**Closed by srikanth-lingala** 2019-08-21 06:03 UTC
